#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

export MUSL_INCLUDE="${MUSL_INCLUDE-/usr/local/lib}"

MACHTYPE="$(uname -m)"
case "${MACHTYPE}" in
  armv6l) ;&
  armv7l) MACHTYPE=arm ;;
  *) ;;
esac

export TSCAT_CFLAGS="-g -Wall -fwrapv -pedantic"
export TSCAT_LDFLAGS="-I$MUSL_INCLUDE/kernel-headers/generic/include -I$MUSL_INCLUDE/kernel-headers/${MACHTYPE}/include"
export CC="musl-gcc -static -Os"
exec make $@
